Database part1
nkanazawa1989/qiskit-ignis pull request #8
Opened 2020-11-10 14:30 UTC by nkanazawa1989

### Summary
PR 1/2
- add database components (PulseTable, ScheduleTemplate)

### Details and comments

2020-11-10 16:15 UTC, eggerdj requested changes
Looks good. Some of the naming can be improved a bit.

2020-11-10 16:15 UTC, eggerdj commented on qiskit/ignis/experiments/calibration/instruction_data/database.py
> +    TABLE_COLS = ['qubits', 'channel', 'inst_name', 'stretch', 'pulse_type',
```suggestion
    TABLE_COLS = ['qubits', 'channel', 'inst_name', 'stretch_factor', 'pulse_type',
```
`stretch` by itself is a little unclear.

2020-11-10 16:15 UTC, eggerdj commented on qiskit/ignis/experiments/calibration/instruction_data/database.py
> +            stretch: Stretch factor of the pulse.
```suggestion
            stretch_factor: Stretch factor of the pulse, typically used for error mitigation.
```
Can you change `stretch` to `stretch_factor` in the rest of the code?

2020-11-10 16:15 UTC, eggerdj commented on qiskit/ignis/experiments/calibration/instruction_data/database.py
> +                format_dict['amp'] *= np.exp(1j * format_dict['phase'])
Will this not give errors if we do e.g. `Drag(**format_dict)` as `Drag` does not accept `phase`?

2020-11-10 16:15 UTC, eggerdj commented on qiskit/ignis/experiments/calibration/instruction_data/database.py
> +            pulse_type: Name of ParametricPulse generator that is used for pulse creation.
This is the name of the pulse envelope right? If so I don't think we should use the `generator` has it already has a strong meaning in the cal module.

2020-11-10 16:15 UTC, eggerdj commented on qiskit/ignis/experiments/calibration/instruction_data/database.py
> +            pulse_type: Name of ParametricPulse generator that is used for pulse creation.
Can you fix this in the other comments too?

2020-11-10 16:15 UTC, eggerdj commented on qiskit/ignis/experiments/calibration/instruction_data/database.py
> +            stretch: Optional[float] = None,
```suggestion
            stretch_factor: Optional[float] = None,
```
and update below

2020-11-10 16:15 UTC, eggerdj commented on qiskit/ignis/experiments/calibration/instruction_data/database.py
> +    def get_dataframe(
perhaps a name like `filter_data` would be more appropriate here?

2020-11-11 01:37 UTC, nkanazawa1989 commented
Thanks!

2020-11-11 08:55 UTC, eggerdj approved these changes
LGTM

2020-11-11 08:56 UTC, merged